# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Image on New Tag

on:
  create:
    tags:
      - '*'

permissions:
  contents: read

jobs:

  dockerfile_lint:
    name: Dockerfile Linting
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./scripts/Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

  build_push_image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: dockerfile_lint
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "{context}/scripts/Dockerfile"
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/ahabid/checker-utilities:latest
            docker.io/ahabid/checker-utilities:${{github.ref_name}}
            ghcr.io/a-h-abid/checker-utilities:latest
            ghcr.io/a-h-abid/checker-utilities:${{github.ref_name}}

  scan_image:
    name: Image Scanning
    runs-on: ubuntu-latest
    needs: build_push_image
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.5.1
        with:
          scan-type: 'image'
          image-ref: 'ghcr.io/a-h-abid/checker-utilities:${{github.ref_name}}'
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
