# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Weekly Scan

on:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read

jobs:
  weekly_scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build an image from Dockerfile
        run: |
          docker build -t ghcr.io/a-h-abid/checker-utilities:${{ github.sha }} -f scripts/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.5.1
        with:
          scan-type: 'image'
          image-ref: 'ghcr.io/a-h-abid/checker-utilities:${{ github.sha }}'
          format: 'sarif'
          ignore-unfixed: true
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
